### ISSUE TITLE
InvalidAuthToken issued

### ISSUE THREAD

**Issue by nstephenh** [pyutil/django-b2#1]
* django-b2 version: 0.5.0
* Django version: 3.0.3
* Python version: 3.7.3
* Operating System: Ubuntu 19.10

### Description

Attempted to upload a file

### What I Did
Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/admin/shop/difiles/add/

Django Version: 3.0.3
Python Version: 3.7.3
Installed Applications:
[...
 'social_django',
 'django_b2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1383, in execute_sql
    for sql, params in self.as_sql():
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1328, in as_sql
    for obj in self.query.objs
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1328, in <listcomp>
    for obj in self.query.objs
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1327, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1278, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/fields/files.py", line 288, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/fields/files.py", line 86, in save
    name = self.field.generate_filename(self.instance, name)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/db/models/fields/files.py", line 307, in generate_filename
    return self.storage.generate_filename(filename)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django/core/files/storage.py", line 364, in _setup
    self._wrapped = get_storage_class()()
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django_b2/storage.py", line 77, in __init__
    self.authorize(application_key_id, application_key)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django_b2/storage.py", line 91, in authorize
    return self.b2.authorize("production", application_key_id, application_key)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/django_b2/backblaze_b2.py", line 32, in authorize
    self.b2_api.authorize_account(name, application_key_id, application_key)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2sdk/api.py", line 160, in authorize_account
    response = self.raw_api.authorize_account(realm_url, application_key_id, application_key)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2sdk/raw_api.py", line 189, in authorize_account
    return self._post_json(realm_url, 'b2_authorize_account', auth)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2sdk/raw_api.py", line 185, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2sdk/b2http.py", line 338, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2sdk/b2http.py", line 308, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2sdk/b2http.py", line 122, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/home/nsh/Documents/Work/CGT/Code/shopcgt/venv/lib/python3.7/site-packages/b2sdk/b2http.py", line 63, in _translate_errors
    post_params,

Exception Type: InvalidAuthToken at /admin/shop/difiles/add/
Exception Value: Invalid authorization token. Server said:  (bad_auth_token)

**Comment by zvolsky** [comment]
Looks like just an authorization problem.
Please run the python3 interpreter and do:

```
from django_b2.backblaze_b2 import BackBlazeB2
b2 = BackBlazeB2()
b2.authorize('production','000xxxxxxxxxxxx000000000x','xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

```
with your credentials.
If this gives an error, you don't have proper credentials. Rewrite them from backblaze correctly.
If this gives no error, make sure you have same credentials in your django settings: B2_APP_KEY_ID, B2_APP_KEY.
(in addition you need set B2_BUCKET_NAME)

You could find the installed package (in virtualenv, site-packages/django_b2) and add a breakpoint into `B2Storage.__init__` after the initial commands which read from setting - to make sure that the code really run with proper your credentials.

**Comment by nstephenh** [comment]
I tried the above in the console, and it worked properly. I edited authorize ran the django code again and it prints my key and key_id 3 times. Upon closer inspection, they were reversed, but not reversed in my .env file. Apparently I was setting them backwards in my IDE. User error strikes again. Thank you for your help!
