### ISSUE TITLE
fixed v0.6.0? bad-auth-token when collectstatic

### ISSUE THREAD

**Issue by j-elmer123** [pyutil/django-b2#3]
* django-b2 version: 0.5.5
* Django version: 2.2.12
* Python version: 3.6 & 3.7
* Operating System: MacOS Catalina 10.15.4

### Description
Trying to collectstatic without defining B2 Credentials.

### What I Did

I put it as is bellow
```
B2_APP_KEY_ID = 'your-app-key-id'
B2_APP_KEY = 'your-app-key'
B2_BUCKET_NAME = 'bucketname'
```

and use specific storage on a specific models.ImageField()
```
from django_b2.storage import B2Storage
...
class HealthCheck(models.Model):
    ...
    image = models.ImageField(
        storage=B2Storage(), blank=True, null=True,
        upload_to=FilenameGenerator("healthcheck"))
```

and when I do `manage.py collectstatic`, the error appear like this
```
% ./manage.py collectstatic
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/elmer/project/django-apps/project/project/apps/bonus_schemes/models.py", line 8, in <module>
    from project.apps.bookings.models import Booking
  File "/Users/elmer/project/django-apps/project/project/apps/bookings/models.py", line 25, in <module>
    from project.apps.partners.models import Partner, PartnerBalanceUpdate
  File "/Users/elmer/project/django-apps/project/project/apps/partners/models.py", line 645, in <module>
    class HealthCheck(models.Model):
  File "/Users/elmer/project/django-apps/project/project/apps/partners/models.py", line 652, in HealthCheck
    storage=B2Storage(), blank=True, null=True,
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/django_b2/storage.py", line 77, in __init__
    self.authorize(application_key_id, application_key)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/django_b2/storage.py", line 91, in authorize
    return self.b2.authorize("production", application_key_id, application_key)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/django_b2/backblaze_b2.py", line 32, in authorize
    self.b2_api.authorize_account(name, application_key_id, application_key)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/b2sdk/api.py", line 160, in authorize_account
    response = self.raw_api.authorize_account(realm_url, application_key_id, application_key)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/b2sdk/raw_api.py", line 189, in authorize_account
    return self._post_json(realm_url, 'b2_authorize_account', auth)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/b2sdk/raw_api.py", line 185, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/b2sdk/b2http.py", line 338, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/b2sdk/b2http.py", line 308, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/b2sdk/b2http.py", line 122, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/Users/elmer/.virtualenvs/project/lib/python3.7/site-packages/b2sdk/b2http.py", line 63, in _translate_errors
    post_params,
b2sdk.exception.InvalidAuthToken: Invalid authorization token. Server said:  (bad_auth_token)
```

My question is, why I need to put my credential when I need to do collect static?

**Comment by zvolsky** [comment]
Hi, j-elmer123. Thank you for reporting this.

1) could you obtain current version: `pip install --upgrade django-b2`
and try 'collectstatic' with it? It should now run because I have changed to lazy initializing and it should now not initialize (include trying to authorize) in such cases like 'collectstatic' is.

2) However I think (but I am not sure) that you will receive authorization error later.
Check if B2_APP_KEY_ID, B2_APP_KEY, B2_BUCKET_NAME contain YOUR PERSONAL values as you receive them on BackBlaze webpage. With YOUR PERSONAL values it should run well.

You could try from pure python or i-python the code from readme, section "Using outside of Django".
Of course again application_key_id, application_key, bucket_name should be YOUR PERSONAL values. You will see if the uploaded file will appear properly on BackBlaze (browse your bucket there).

**Comment by pyutil** [comment]
>> j-elmer123: could you confirm if it is better now? thank you.

**Comment by j-elmer123** [comment]
> > > j-elmer123: could you confirm if it is better now? thank you.

Yes, 0.6.0 fix my problem. thank you

**Comment by j-elmer123** [comment]
btw my credential in `settings.py` is only dummy credentials as initializer only, my real credentials are in another git ignored file

**Comment by pyutil** [comment]
ok, I'm closing this.
